name: Build OLLVM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install cmake ninja-build python

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" ..

    - name: Build
      run: |
        cd build
        ninja
